### ISSUE TITLE
Transfer ownership to JuliaArrays

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/FillArrays.jl#1]
@SimonDanisch I've made a preliminary version.  Do you think the name is appropriate? `Eye` is slightly outside the mould, though it is arguably a diagonal fill matrix.

Are you happy for it to be transferred?

**Comment by SimonDanisch** [comment]
Sure! :) 
I have a few comments, but I think that shouldn't hold anything back.

E.g., shouldn't e.g. `Ones` be defined as `Ones{T}(ns...) where T = Fill{T}(one(T), ns...)` or is there a reason why they need to be separate types? Also, I imagined to make the conversions work via the generator/collect `API` - but I haven't really had time to look in the difficulties with that approach.

**Comment by dlfivefifty** [comment]
Zeros is definitely special so should not be defined as a Fill.

Ones is less special, but I made it it’s own type for consistency.
