### ISSUE TITLE
Lazy version of repeat?

### ISSUE THREAD

**Issue by JeffFessler** [JuliaArrays/FillArrays.jl#112]
The `Fill` types in this package are a special case of `repeat`, e.g.,
`fill(0, 2, 3)` and `repeat([0], 2, 3)` and  `zeros(Int64, 2, 3)` are all identical.

I have a use case for a lazy version of a more general version, i.e., `repeat(x, dims...)` where `x` is a medium sized array that fits comfortably in memory but the `repeat` version uses a lot more memory needlessly.

I did a web search for "julia lazy repeat array" and the top hit was to
https://github.com/JuliaArrays/LazyArrays.jl
so it seems that all paths lead back to @dlfivefifty :)

Would a `Repeat` type belong here in `FillArrays` or over in `LazyArrays` or somewhere else completely?
Or does it already exist somewhere? 

For my own purposes, if I had `mask = Repeat(mask2, dims...)` then the only operations I would need are `x .* mask` and `x[mask]`.

**Comment by dlfivefifty** [comment]
It's easy to add to LazyArrays.jl by just filling in some missing information:
```julia
julia> Base.ndims(::Applied{<:Any,typeof(repeat),Tuple{Vector{Int},Int}}) = 1

julia> Base.size(A::Applied{<:Any,typeof(repeat),Tuple{Vector{Int},Int}}) = (length(A.args[1]) * A.args[2],)
julia> Base.eltype(A::Applied{<:Any,typeof(repeat),Tuple{Vector{Int},Int}}) = eltype(A.args[1])

julia> ApplyArray(repeat, [0], 2)
2-element ApplyArray{Int64,1,typeof(repeat),Tuple{Array{Int64,1},Int64}}:
 0
 0
```
You could then add a fast `getindex`. So that might be the easiest for now.

**Comment by JeffFessler** [comment]
Thanks for this super helpful reply.  I started working on it, but ran into issues because what I want is a subtype of `AbstractArray` and it seems that `Applied` and `ApplyArray` types are not.  I read a few of the issues over at LazyArrays and saw that there are concerns about type stability because you don't know the return element type of `f(...)` in general, if I understood correctly.  For `repeat` of course we do know that type.  I'll have to think about this more.  For posterity here is how far I got:

```julia
using LazyArrays

_repeat(x, dims) = repeat(x, dims...) # repeat does not accept a tuple :(

const Repeat = Applied{A, typeof(_repeat), D} where {A <: Any, D <: Tuple}

Base.ndims(r::Repeat) = max(ndims(r.args[1]), length(r.args[2]))

function Base.size(r::Repeat)
    xsize = size(r.args[1])
    dims = r.args[2]
    pad = (a, b) -> (a..., ones(Int, max(length(b)-length(a),0))...)
    return (pad(xsize,dims)...,) .* (pad(dims,xsize)...,)
end

Base.eltype(r::Repeat) = eltype(r.args[1])

# IndexStyle(::Repeat) = IndexCartesian() # default for AbstractArray

function Base.getindex(r::Repeat, ks::Vararg{Int,N}) where N
    ndims(r) == length(ks) || throw(BoundsError())
    dims = r.args[2]
@show ks
    if all(dims[1:(N-1)] .== 1) # for my use case 
        return r.args[1][ks[1:(N-1)]...] # ignore last (repeat) dimension
    end
    return materialize(r)[ks...] # otherwise revert
end

function Base.getindex(r::Repeat, k::Int)
@show k
    return materialize(r)[k] # just for testing
end

# this would not be needed for an AbstractArray:
function Base.getindex(r::Repeat, I::UnitRange{Int})
@show I
    [r[i] for i in I]
end
```

**Comment by dlfivefifty** [comment]
I don't think you've understood. ` ApplyArray ` is definitely ` <: AbstractArray ` and the overload of ` eltype ` ensures that it is type inferred.

**Comment by JeffFessler** [comment]
Thanks for the reply.  I definitely did not understand.  I guess I tried to run before I walked by generalizing to more dimensions before understanding the 1D case.  I've generalized your example code to handle arbitrary vectors now instead of just `Vector{Int}` and that is working fine.  But I am stuck on the `getindex` part.  Your example code above used `::Applied` but my sense is that I need to overload `getindex` for an `ApplyArray` type, right? My attempt to do partially worked in the sense that `getindex(a, 3)` calls my function, but `a[3]` still calls line 193 in lazyapplying.jl which baffles me because I thought from the Julia manual that `a[3]` gets translated by the complier into `getindex`.  Here's my code so far.

```julia
const RepeatA = Applied{A, typeof(repeat), Tuple{V,Int}} where {A <:Any, V <: AbstractVector}
Base.ndims(::RepeatA) = 1
Base.size(r::RepeatA) = (length(r.args[1]) * r.args[2],)
Base.eltype(r::RepeatA) = eltype(r.args[1])

const RepeatAA{T,N} = ApplyArray{T, N, typeof(repeat)} 
Base.@propagate_inbounds function getindex(r::RepeatAA{T,1}, k::Int) where {T}
@show k # debugging
    return r.args[1][mod1(k,length(r.args[1]))]
end
x = 0:3
dim = 2
a = ApplyArray(repeat, x, dim)

@show a isa RepeatAA # true

@which getindex(a, 3) # this calls my getindex above
@assert getindex(a, 3) == r[3]
@which a[4] # this goes to lazyapplying.jl:193 !?
a[4]
```

**Comment by dlfivefifty** [comment]
You want ` Base.getindex `. Think you are making a new function called ` getindex `...

**Comment by JeffFessler** [comment]
Oh how embarrassing.  With that help I got it to work and I generalized it to arbitrary vectors.  The need to use `Applied` type for some functions and `ApplyArray` type for `getindex` was non-obvious to me.
Unfortunately, some overhead somewhere is making this much slower (for `.*`) than just using the full `BitArray.`
I tried to use the Profiler to study it but I didn't really get insight from its output.
Perhaps I'd see a bigger difference in my actual use case which is a 2D array that is repeated to make a 3D array that is probably too big to fit in the cache.  Comments welcome if you see any obvious performance opportunities...  Thanks again for your help.

```julia
using LazyArrays
using BenchmarkTools

# generalization to arbitrary (1D) vectors:
const RepeatA = Applied{A, typeof(repeat), Tuple{V,Int}} where {A <:Any, V <: AbstractVector}
Base.ndims(::RepeatA) = 1
Base.size(r::RepeatA) = (length(r.args[1]) * r.args[2],)
Base.eltype(r::RepeatA) = eltype(r.args[1])

const RepeatAA{T,N} = ApplyArray{T, N, typeof(repeat)}
Base.@propagate_inbounds function Base.getindex(r::RepeatAA{T,1}, k::Int) where {T}
#   @boundscheck checkbounds(r, k)
    return r.args[1][mod1(k,length(r.args[1]))]
end

mask1 = trues(2^20)
mask1[1] = false
dim = 2
r = repeat(mask1, dim)
a = ApplyArray(repeat, mask1, dim)

if true
    x = rand(size(r)...)
    y = copy(x)
    function dotter!(y, x, mask)
        y .= x .* mask
    #   broadcast!(*, y, x, mask) # same @btime results
    end
    @assert dotter!(y, x, r) == dotter!(y, x, a) == x .* r
    @btime dotter!($y, $x, $r) # 1.8 ms using full `BitArray`
    @btime dotter!($y, $x, $a) # 8.6 ms using `ApplyArray` :(
end
```

**Comment by dlfivefifty** [comment]
Note in your example it's still accessing memory so I can't see how it could ever be faster than just allocating a bigger array, and is likely slower as `mod1` is more expensive than just directly accessing memory. 

Try with a lazy argument and it may be a different story, though with lazy arrays it's always a stiff competition between communication speed with memory and CPU speed in regenerating the entries, so it's not uncommon for non-lazy analogues to be faster.

**Comment by dlfivefifty** [comment]
You could try a fully lazy version to see how it does:
```julia
mask1 = Vcat(false, Trues(2^20 - 1))
```
Though this depends on `broadcast` unpeeling the `Vcat` to avoid having to test which argument contains the entry: this is already implemented for some special cases of broadcasting

https://github.com/JuliaArrays/LazyArrays.jl/blob/3dfb6f05bb39786a0a9654252376107ffa63fcf4/src/lazyconcat.jl#L303

 so may just work automatically, though haven't really tested with in-place broadcasting and may not work for your case.

**Comment by JeffFessler** [comment]
Thanks for the suggestion, but what I would need is something like a more general `cat(dims=3, ...)` not just a `vcat`.  Your point about non-lazy versions being faster reminded me that here I am using `BitArrays` which use 8x less memory than the a regular Bool array, making them very cache friendly and thus especially hard to beat with a lazy version.  So I am going to drop this for now.  But if someone later has a better use case for a `RepeatArray` then perhaps the discussion above will help them get started.  Thanks again.

**Comment by JeffFessler** [comment]
@dlfivefifty I wanted to let you know that, thanks to the help you gave above,
I was able to use `ApplyArray` to make a lazy version of `ndgrid`:
https://github.com/JuliaImageRecon/ImageGeoms.jl/blob/main/src/ndgrid.jl
I thought about offering it as a PR here, but my sense (from discourse) is that the
Julia community really discourages using `ndgrid`.
It's not a full-featured lazy version of `repeat` but it can be a low-memory alternative to `ndgrid`
when one is being, well, lazy...

**Comment by dlfivefifty** [comment]
Cool. I'd be open to a PR if you feel it's an appropriate place for it (I can see the case).
