### ISSUE TITLE
FillArrays 0.10 broadcasting bug (?) that breaks ReverseDiff compatability

### ISSUE THREAD

**Issue by mohamed82008** [JuliaArrays/FillArrays.jl#125]
The following behaviour is not expected and breaks ReverseDiff when broadcasting arrays and fill arrays in a function that it's differentiating:
```julia
julia> Base.broadcasted(-, rand(3), Zeros(3))
3-element Vector{Float64}:
 0.24941130160268532
 0.6830968360570726
 0.833154238638848
```
`Base.broadcasted` should return a `Base.Broadcast.Broadcasted` instance.

Ref: https://github.com/JuliaDiff/ReverseDiff.jl/issues/156

**Comment by devmotion** [comment]
I'm not sure if this is actually an issue of FillArrays. The [Julia docs](https://docs.julialang.org/en/v1/manual/interfaces/#extending-in-place-broadcast) mention explicitly that sometimes you might want to avoid the default machinery and perform optimizations by implementing `broadcasted`.

**Comment by mohamed82008** [comment]
But the default machinery is assumed in ReverseDiff and Tracker. If FillArrays wants to have an optimisation there, it can replace the `-` with a function that takes 2 arguments and returns the first one. This should be optimised away by the compiler where `-` may not. Otherwise, we break MvNormal autodiff with ReverseDiff and Tracker because it uses FillArrays and broadcasting.

**Comment by mohamed82008** [comment]
The broadcasting implementation in ReverseDiff and Tracker is not trivial to change in a generic and correct way.

**Comment by dlfivefifty** [comment]
No you should not assume `broadcasted` returns a `Broadcasted`:
```julia
julia> Base.broadcasted(+, 1:5, 1)
2:6
```

**Comment by mohamed82008** [comment]
FYI: this is breaking a significant portion of the PPL ecosystem right now.

**Comment by dlfivefifty** [comment]
We are following the behaviour of ` AbstractRange `. Perhaps you can use a custom broadcast style?

**Comment by mohamed82008** [comment]
We rely on calling `flatten` over the output `Broadcasted` struct to get a scalar function that can be broadcasted over the array arguments for which a custom adjoint is defined. ReverseDiff and Tracker can't differentiate functions wrt structs so it needs arrays and numbers as inputs. What FillArrays 0.10 does is:
```julia
Base.Broadcast.flatten(Base.broadcasted(abs2, Base.broadcasted(-, rand(3), Zeros(3)))).f === abs2 # true
```
which is a 1-arg function so we can't just broadcast it over the inputs `rand(3)` and `Zeros(3)`.

**Comment by dlfivefifty** [comment]
Just add something like
```Julia
_flatten(a) = a
_flatten(a::Broadcasted) = flatten(a)
```

**Comment by mohamed82008** [comment]
Fixed downstream https://github.com/JuliaDiff/ReverseDiff.jl/pull/157.
