### ISSUE TITLE
`Base.getindex(x::AbstractArray{T,N}, mask::Trues{N, NTuple{N,Base.OneTo{Int}}})` is downstream chaos

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/FillArrays.jl#162]
Found in the ambiguity detection in SciMLBase after a FillArrays.jl dependency was added:

https://github.com/SciML/RecursiveArrayTools.jl/runs/3752855248#step:6:202

The issue stems from `Base.getindex(x::AbstractArray{T,N}, mask::Trues{N, NTuple{N,Base.OneTo{Int}}})` types of definitions. The abstract array interface is defined as https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array . This has definitions `getindex(A, I...)` and `setindex!(A, X, I...)` specific to the array `A`, but possibly non-specific to the type `I`. To handle some ambiguities we distinguish over a decently sized set:

https://github.com/SciML/SciMLBase.jl/blob/master/src/solutions/solution_interface.jl#L31-L32

but adding FillArrays to the set still fails:

https://github.com/SciML/SciMLBase.jl/pull/105

I think downstream packages defining any overloads of the form `Base.getindex(x::AbstractArray{T,N}, I::T)` where `T` is the new package thing will cause ambiguity issues and require all downstream array types to define the intersection method `Base.getindex(x::A, I::T)`, which means the only way it can be handled correctly is for type package `T` to be a dependency of all downstream array packages `A` (😱). To me that doesn't sound like a tenable solution.

On top of that, I would presume that this definition, since it introduces ambiguities into all of these downstream "open indexing" definitions, it's also invalidating a ton of downstream `getindex` and `setindex!` operations as well. So it's likely not just an issue causing ambiguity errors but also hitting compile times.

Maybe @timholy or @mbauman have an opinion on whether these overloads are okay. I would think the right thing would be to remove them.

**Comment by dlfivefifty** [comment]
This is a common case of a bad overload that causes problems. Perhaps for now we change it to only `N = 1`, `N = 2`, and `N = 3`?

**Comment by ChrisRackauckas** [comment]
I think specializing on a few might work.

**Comment by timholy** [comment]
When specializing on the indices rather than the array, it's better to specialize `to_index` or `to_indices`. I would try deleting all of these methods:
https://github.com/JuliaArrays/FillArrays.jl/blob/eb8df92a8ceede7689ff72b2738c1c8bef161ab5/src/trues.jl#L26-L54

and replacing them with `to_indices(A, I) = LinearIndices(A)` (with appropriate types on `I`).

**Comment by dlfivefifty** [comment]
@timholy I don't see how that could work in this case as we need to do something special with `y` and `x` for a special type of indices. Doesn't `setindex!` have to be overloaded somewhere?

**Comment by timholy** [comment]
Tell that to CI :smile: (see #163)
