### ISSUE TITLE
Specialize A * Eye and Eye * A

### ISSUE THREAD

**Issue by cossio** [JuliaArrays/FillArrays.jl#168]
```
d = Diagonal(Ones(10))
```

The following ops fallback to generic (diagonal) matrix multiplies.

```julia
d * randn(10, 10)
randn(10, 10) * d
```

A faster fallback is possible since `d` is just the identity matrix.

**Comment by dlfivefifty** [comment]
It already does a faster fallback, lowering to broadcasting:

https://github.com/JuliaLang/julia/blob/85a6990a9c1d49dd5aeaffeb4b38f881dc120823/stdlib/LinearAlgebra/src/diagonal.jl#L279

**Comment by cossio** [comment]
How's that faster than just returning the other term?

```
d = Diagonal(Ones(10))
A = randn(10,10)
d * A # should just return A
```
