### ISSUE TITLE
`nxn Fill` addition `UniformScaling` errors

### ISSUE THREAD

**Issue by theogf** [JuliaArrays/FillArrays.jl#170]
Here is a MWE:
```julia
julia> K = Fill(1.0, 2, 2)
julia> K + 1e-6 * I
ERROR: ArgumentError: Cannot setindex! to 1.000001 for an AbstractFill with value 1.0.
Stacktrace:
 [1] setindex!
   @ ~/.julia/packages/FillArrays/Vzxer/src/FillArrays.jl:53 [inlined]
 [2] +(A::Fill{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, J::UniformScaling{Float64})
   @ LinearAlgebra ~/julia-1.7.1/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:219
 [3] top-level scope
   @ REPL[28]:1
```
Observed at https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/432

**Comment by dlfivefifty** [comment]
Always include the full stack trace as otherwise we can't see where the error is

**Comment by theogf** [comment]
Updated! Matrix addition with a `UniformScaling` creates a new matrix of the same type of the matrix and adds the values in place.

**Comment by dlfivefifty** [comment]
OK so probably we need to overload `+(::Fill, ::UniformScaling)` and varients

**Comment by devmotion** [comment]
I opened a PR that fixes the issue: https://github.com/JuliaArrays/FillArrays.jl/pull/171
