### ISSUE TITLE
Tag v1.0

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/FillArrays.jl#204]
I noticed this package hasn't had a breaking change in a year. Let's tag v1.0.

If any one wants breaking changes before this please let me know in the next week.

**Comment by jishnub** [comment]
I have one suggestion: `FillArrays` should store their lengths in the type. This will help in understanding whether an array is infinite from the type, which is what we need for traits like `Base.IteratorSize`. Currently, this isn't implemented correctly, and infinite `FillArrays` are treated the same as finite ones in the iterator protocol.

**Comment by dlfivefifty** [comment]
Thanks! I think as a general rule its best to keep the type as simple as possible
