### ISSUE TITLE
add `ones` and `eye`here

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/FillArrays.jl#22]
This would be a natural home for the deprecated `ones` and `eye` commands, due to

https://github.com/JuliaLang/julia/pull/24438

@Sacha0 Is there any reason that including these is a "bad" idea?

**Comment by Sacha0** [comment]
> Is there any reason that including these is a "bad" idea?

*backs away slowly*

😉

**Comment by dlfivefifty** [comment]
I'm closing it as no one seems to need it.
