### ISSUE TITLE
0.13.8 breakage

### ISSUE THREAD

**Issue by theogf** [JuliaArrays/FillArrays.jl#224]
The 0.13.8 release broke this basic MWE...
```
x = rand(3, 3)
X = Fill(x, 10)
X + X
ERROR: DimensionMismatch: arrays could not be broadcast to a common size; got a dimension with lengths 10 and 3
```
This comes from the new `fill_add` using broadcasting for some reason that escapes me.

[EDIT:] Corrected code snippet

**Comment by JordiManyer** [comment]
Same issue in [Gridap.jl](https://github.com/gridap/Gridap.jl/issues/889) 

Is this a feature or a bug?

**Comment by jishnub** [comment]
Definitely a bug @putianyi889

**Comment by putianyi889** [comment]
no need to limit eltype. I'll fix it.

**Comment by putianyi889** [comment]
For a quick fix, use `X .+ X`.
