### ISSUE TITLE
"Docs: Stable" link in README  is broken

### ISSUE THREAD

**Issue by jakobnissen** [JuliaArrays/FillArrays.jl#240]
It seems the documentation is only built for `dev`.

**Comment by jishnub** [comment]
@dlfivefifty it's possibly that the `DOCUMTENTER_KEY` SSH key isn't added to this repo

**Comment by dlfivefifty** [comment]
I've added the keys, anything else need to be done?

**Comment by jishnub** [comment]
I think this should be enough, and the documentation should be generated on the next stable release

**Comment by jishnub** [comment]
This is fixed now
