### ISSUE TITLE
Bad indexing in latest version

### ISSUE THREAD

**Issue by cstjean** [JuliaArrays/FillArrays.jl#26]
With FillArrays 0.2.0:

```julia
julia> using FillArrays

julia> Fill(10, 5)[[true, true, false, true, false]]
5-element Fill{Int64,1,Tuple{Int64}}:
 10
 10
 10
 10
 10

julia> fill(10, 5)[[true, true, false, true, false]]
3-element Array{Int64,1}:
 10
 10
 10
```

**Comment by dlfivefifty** [comment]
I don't understand either behaviour: `false == 0` so shouldn't they both throw out of bounds errors?

**Comment by dlfivefifty** [comment]
Ah OK, Bool indexing is special:
```julia
julia> fill(10, 5)[[true, true, false, true, false]]
3-element Array{Int64,1}:
 10
 10
 10

julia> fill(10, 5)[[1,1,2,1,2]]
5-element Array{Int64,1}:
 10
 10
 10
 10
 10

julia> fill(10, 5)[[1,1,0,1,0]]
ERROR: BoundsError: attempt to access 5-element Array{Int64,1} at index [[1, 1, 0, 1, 0]]
Stacktrace:
 [1] throw_boundserror(::Array{Int64,1}, ::Tuple{Array{Int64,1}}) at ./abstractarray.jl:484
 [2] checkbounds at ./abstractarray.jl:449 [inlined]
 [3] _getindex at ./multidimensional.jl:588 [inlined]
 [4] getindex(::Array{Int64,1}, ::Array{Int64,1}) at ./abstractarray.jl:905
 [5] top-level scope at none:0
```

**Comment by cstjean** [comment]
Right. That's how syntax like `arr[isodd.(arr)]` works.

**Comment by dlfivefifty** [comment]
Seems like a bad idea... (or, maybe `Bool <: Integer` is bad).... so we want something like
```julia
function getindex(A::AbstractFill, kr::AbstractVector{Bool)
   length(A) == length(kr) || throw(DimensionMismatch())
   Fill(getindex_value(A), count(kr))
end
function getindex(A::AbstractFill, kr::AbstractArray{Bool)
   size(A) == size(kr) || throw(DimensionMismatch())
   Fill(getindex_value(A), count(kr))
end
```

**Comment by dlfivefifty** [comment]
(We actually could use a function `similar_fill(A)` that returns `Ones`, `Zeros`, or `Fill` appropriately.)

**Comment by cstjean** [comment]
Or maybe `Ones` should be `Ones(n) = Fill(One(), n)`.

**Comment by dlfivefifty** [comment]
You mean add a new type called `One`? Perhaps.

Note that `Ones` is special (I remember there being some debate before whether it's necessary):
```julia
julia> cumsum(Ones{Int}(5))
Base.OneTo(5)

julia> cumsum(Fill(1,5))
1:1:5

julia> cumsum(Fill(2,5))
2:2:10
```

**Comment by cstjean** [comment]
Yeah. I'd be curious to see where the `OneTo` optimization matters, but FWIW, we could still special-case on One:  `cumsum(f::Fill{One}) = OneTo(length(f))`

**Comment by dlfivefifty** [comment]
I use it in ApproxFun for working out the block sizes of tensor products of block vectors. Having it special cased allows for faster lookup of blocks.

**Comment by dlfivefifty** [comment]
` One{T} ` and `  Zero{T} ` would be nice to have in other settings too.

**Comment by timholy** [comment]
(I haven't been using this package---yet---but I stumbled across this in a search for all Julia packages that might be overloading `Base._getindex`)

The real issue is presumably that you're providing `getindex` methods for anything besides `Integer` indexes. Julia's indexing operations are complex---do you really want to write out methods for `F[3, CartesianIndex(3, 2), [1 2; 3 4], [1,3,7]]` yourself? (Yes, we support multidimensional indexes and they all do something different, with a very clearly thought out design.) Logical indexing has been a core part of Julia's indexing operations since the beginning (and got really good in 0.4 or so).

You should strenuously avoid adding such methods unless there is really, really no alternative.

**Comment by cstjean** [comment]
I don't quite understand the objection. The `AbstractArray` inheritance provides (slow) generic fallbacks for all the fancy base indexing. What's the harm in providing fast implementations of some specific operations like `getindex(::Fill, ::UnitRange1D)`?

`Bool <: Integer` is a questionable decision in Base, which is what caused this issue, but it's easy enough to fix.

**Comment by timholy** [comment]
Once you do, you're responsible for implementing everything. But looking closer I see this package faces the obstacle of immutability. So you may be forced to.

At a minimum, you should study how it works in Base and mimic its operations quite precisely. That's easiest to do if you just step in to the default methods and see how they work (e.g., using Rebugger or Gallium on older versions of Julia).

**Comment by cstjean** [comment]
> Once you do, you're responsible for implementing everything.

Why?

**Comment by timholy** [comment]
Because you've intercepted the dispatch heirarchy? Just for those types, of course.

**Comment by timholy** [comment]
But yes, I agree that `Bool<:Integer`

**Comment by dlfivefifty** [comment]
I agree with Tim that we should follow Base as closely as possible, but I don’t have time at the moment to address this.

**Comment by cstjean** [comment]
> One{T} and Zero{T} would be nice to have in other settings too.

I wonder whether `getindex(::Fill{One{Int}}, ::Int)` should be `one(Int)` or `One{Int}()`. The latter gives additional opportunities for simplification, but would be a breaking change, and we'd have to write functions like `sin(::One{T}) = sin(one(T))`. It doesn't sound feasible. Or is that something that the promotion system can handle?

OTOH, if `Fill(One{Int}(), 2)[1]` returns `1`, that's an ugly special case. We could have that `One` is an unexported implementation detail.

**Comment by dlfivefifty** [comment]
I don't think `One` and `Zero` are going to help here: the `eltype` of
```julia
Fill(One{Int}(), 10)
```
would need to be `One{Int}` for consistency.

**Comment by cstjean** [comment]
Then how would `sin.(Ones(10))` work out? Don't we have to define `sin(::One)`? That's an endless task.

**Comment by dlfivefifty** [comment]
That's why I'm saying I don't think the idea of using `One` and `Zero` is going to work. It's a bad design if `Fill(::One,...)` is special cased.
