### ISSUE TITLE
Can't convert to a `ZerosMatrix` to `Diagonal`

### ISSUE THREAD

**Issue by samuelsonric** [JuliaArrays/FillArrays.jl#282]
MWE:

```julia
using LinearAlgebra
using FillArrays

convert(Diagonal{Bool, Vector{Bool}}, Zeros(2, 2))
```
throws the following: `MethodError: no method matching Vector{Bool}(::Zeros{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}})`.

Presumably, this would be fixed by rewriting [Line 511 of FillArrays.jl](https://github.com/JuliaArrays/FillArrays.jl/blob/41715aa8afc1a86b54d458faa73c3ea8e5639c00/src/FillArrays.jl#L511) like so:
```julia
T(A::AbstractFillMatrix) where T <: Diagonal = T(diag(A))
```

Thanks!

**Comment by samuelsonric** [comment]
Here's another one:

```julia
using FillArrays
T = typeof(Zeros(2))

convert(T, Fill(0, 2))
```

This outputs `MethodError: Cannot `convert` an object of type Fill{Int64, 1, Tuple{Base.OneTo{Int64}}} to an object of type Zeros{Float64, 1, Tuple{Base.OneTo{Int64}}}`.

**Comment by jishnub** [comment]
This is a `LinearAlgebra` issue. Note that the following doesn't work either:
```julia
julia> convert(Diagonal{Bool, Vector{Bool}}, zeros(2, 2))
ERROR: MethodError: no method matching Vector{Bool}(::Matrix{Float64})
[...]
```
(this is the error on Julia v1.10.0-alpha1 and an 8-day old nightly)
