### ISSUE TITLE
`AbstractZeros`/`AbstractOnes`

### ISSUE THREAD

**Issue by mtfishman** [JuliaArrays/FillArrays.jl#298]
What do you think of introducing `AbstractZeros <: AbstractFill`/`AbstractOnes <: AbstractFill`, with `Zeros` and `Ones` as subtypes? It would make it easier to define custom types that act like `Zeros` and `Ones`.

An application we have in mind in [ITensors.jl](https://github.com/ITensor/ITensors.jl) is having a type that mostly acts like `Zeros` but also has a type parameter which defines how it would be allocated (say allocated onto CPU or GPU if you call `collect`). It would be nice to automatically inherit most of the behavior of the `Zeros` type in this package.

**Comment by dlfivefifty** [comment]
Hmm I’m not immediately convinced it’s worth it but I suppose there’s no obvious negative consequence of this…

**Comment by mtfishman** [comment]
I guess at least it is worth it for us so we don't have to copy and paste all of the code defined for `Zeros` into our package, there are a number of nice optimizations for algebra/broadcasting involving `Zeros` we want to take advantage of.

I suppose the main non-trivial consideration I see would be deciding what the minimal interface is for an `AbstractZeros`/`AbstractOnes` type but that seems like something that could be worked out over time. It seems like the main thing our `AbstractZeros` type would need to overload is `fillsimilar` in order to preserve the allocation type.

I'm happy to make a PR.

**Comment by dlfivefifty** [comment]
I guess one concern is there are other types with similar issues, like ` UnitRange ` 

are you sure that your design is the “right” one? Maybe passing along a flag would be more natural?

**Comment by mtfishman** [comment]
I think that would be a lot more complicated. We want to pass this `Zeros` type through code that is written generically for `AbstractArray` (as a backend for a generic tensor type that can have all sorts of underlying data structures). That would mean that every operation involving this `Zeros` type would need to accept that flag, which may not even be possible, i.e. passing it through external generic functions. We may keep it unallocated through a number of operations (like tensor contractions, additions, etc.), and even change it back and forth (lazily) from CPU to GPU, and then eventually allocate it as needed, and we want to keep track of where and how it should be allocated when we need to allocate it.

**Comment by mtfishman** [comment]
If there was an `AbstractZeros` type we could inherit behavior from, I think it would just be a few lines of code (like overloading `fillsimilar`) to make our new `Zeros` type work through all of those operations, while keeping track of the allocation type. There would need to be some type/operator promotion rules for how different allocation types interact with each other in binary operations like matrix multiplication and addition, but we already have that logic since it's the same whether or not the data is allocated, if you work that logic out at the type level.

**Comment by mtfishman** [comment]
I've been meaning to look into `ArrayLayouts.jl`. We have our own (slightly ad hoc) system for determining the output types and structures of tensor operations like contractions and additions. We have a variety of n-dimensional tensor backends like dense, block sparse, diagonal, etc. and need to determine what the output structure will be for various combinations of those. `ArrayLayouts.jl` may give a nicer approach for doing that.

**Comment by dlfivefifty** [comment]
I'm happy to walk you through the design of ArrayLayouts.jl. I will mention though that it has to overload a lot of Base/LinearAlgebra routines which has some consequences: there are occasionally unexpected ambiguities where an overload was missing.

But one feature that might be particularly helpful is that fallback routines can take advantage of sparsity.

**Comment by mtfishman** [comment]
Thanks, I think for now I will take a look at the design and think about how it might mesh with our current design. I'll let you know if I have questions about it.

Also, what do you think about additionally having an `AbstractOneElement`, for similar reasons as above?

**Comment by dlfivefifty** [comment]
> Also, what do you think about additionally having an AbstractOneElement, for similar reasons as above?

This is exactly why I'm concerned with your design: you end up needing abstract versions of _every_ type. But I'll defer to others: either we do this for all the types you need or none of them.

**Comment by dlfivefifty** [comment]
Also: its possible changing the function signatures may lead to lots of ambiguities downstream. I'm not sure this counts as breaking or not but something to be aware of.

**Comment by mtfishman** [comment]
I'll make a minimal PR with just `AbstractZeros`/`AbstractOnes` for now (just changing function signatures). Maybe can test some downstream packages against that PR.

**Comment by dkarrasch** [comment]
Seems like this is closed by #299?

**Comment by mtfishman** [comment]
Closed by #299.
