### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/FillArrays.jl#3]
It says I don't have enough rights to enable Travis

@SimonDanisch

**Comment by SimonDanisch** [comment]
I added it on travis and appveyor... If you need more rights let me know! After having the bad habit of adding everyone as an admin to the orgs I'm part of, I started being a bit more careful with rights :)

**Comment by dlfivefifty** [comment]
Thanks! Don't worry about adding more rights, I'll just ping you if there are any other issues.

PS Just tried it out in 0.7, there's a new deprecation of `eye(n, m)` in favour of `Matrix(I, n, m)`, which is consistent with what we are doing!
