### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by r-barnes** [JuliaArrays/FillArrays.jl#32]
Does this package provide an array type that (roughly speaking) takes only as much memory as is needed to store a single element, but allows access to the full range of the array by returning copies of that element as needed? (The word "lazy" is unclear to me.)

**Comment by cstjean** [comment]
It's an immutable data structure, but you can "instantiate it" with `collect` into a regular vector.

```julia
julia> using FillArrays

julia> fa = Fill(5.0, 10);

julia> fa[1] = 2
ERROR: setindex! not defined for Fill{Float64,1,Tuple{Int64}}
Stacktrace:
 [1] error(::String, ::Type) at ./error.jl:42
 [2] error_if_canonical_setindex(::IndexLinear, ::Fill{Float64,1,Tuple{Int64}}, ::Int64) at ./abstractarray.jl:1014
 [3] setindex!(::Fill{Float64,1,Tuple{Int64}}, ::Int64, ::Int64) at ./abstractarray.jl:1005
 [4] top-level scope at none:0

julia> vect = collect(fa)
10-element Array{Float64,1}:
 5.0
 5.0
 5.0
 5.0
 5.0
 5.0
 5.0
 5.0
 5.0
 5.0

julia> vect[1] = 333
333

julia> vect
10-element Array{Float64,1}:
 333.0
   5.0
   5.0
   5.0
   5.0
   5.0
   5.0
   5.0
   5.0
   5.0
```

**Comment by cstjean** [comment]
> Does this package provide an array type that (roughly speaking) takes only as much memory as is needed to store a single element,

Yes, that's exactly what it is. It just stores the element + the length of the array.
