### ISSUE TITLE
Support Array Slicing

### ISSUE THREAD

**Issue by lstagner** [JuliaArrays/FillArrays.jl#33]
I got bit by this yesterday. The solution is to write a custom `getindex(A,I...)` method but I am unsure about how to do that generically.

```
julia> x = Zeros(3,3)
3×3 Zeros{Float64,2,Tuple{Int64,Int64}}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> x[:,1]
3-element Array{Float64,1}:
 0.0
 0.0
 0.0

julia> x[1:3,1]
3-element Array{Float64,1}:
 0.0
 0.0
 0.0
```

**Comment by dlfivefifty** [comment]
See Tim Holy's comments in https://github.com/JuliaArrays/FillArrays.jl/issues/26

Essentially one should step through every `getindex` implementation in Base and override it here. Probably ranges provide a blue print. 

If you make a PR I'll gladly merge it.

**Comment by dlfivefifty** [comment]
This has been implemelented:
```julia
julia> x = Zeros(3,3)
3×3 Zeros{Float64}

julia> x[:,1]
3-element Zeros{Float64}

julia> x[1:3,1]
3-element Zeros{Float64}
```
