### ISSUE TITLE
Conversion from array

### ISSUE THREAD

**Issue by cstjean** [JuliaArrays/FillArrays.jl#38]
What would you say to supporting `convert(Fill, [2.0,2.0,2.0])`, and throwing an error if it's not uniformly the same value?

**Comment by cstjean** [comment]
I can see an issue with empty vectors: `convert(Fill, String[])`. We can use `Fill("any string", 0)`. But how do we get an instance of some arbitrary type `T`, to put in the `value` field? `one(T)/zero(T)/...` might not be defined. 

Solution 1: use `#undef`, which we could do if the inner constructor could call `new(axes=axes)`, but `new` doesn't do that yet. So we'd have to shuffle the field order so that `value` can be `#under`, which is unappealing.

Solution 2: have a function `any_value(::Type{T}) where T<:Number = oneunit(T)`, that gives us that value. It works, but it's ugly.

Solution 3: throw an error on empty vectors.

Do you see anything else?

**Comment by dlfivefifty** [comment]
Just throw an error I think. Though I’m not sure what the use case for this is.

Note you should also add variants like ` convert(AbstractFill{T} , v) `
