### ISSUE TITLE
Lazy fill from a function

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/FillArrays.jl#5]
I think it would be nice to be able to give a function `(i,j)` and have a fill array be created from that. Example: Strang Matrix:

```julia
FillArray((i,j)-> i==j ? -2 : abs(i-j) == 1 ? 1 : 0,5,5)
```

**Comment by SimonDanisch** [comment]
I was also thinking, that the main type shouldn't hold the value, but instead a function it calls on getindex... I did a quick experiment, but stopped when I run out of time...

**Comment by dlfivefifty** [comment]
In my setting, the main thing is to know the structure of the matrix from the type: for example `Fill(x, n, m)` is a rank 1 matrix.  

I could see a use for a `LazyArray`, in this package or elsewhere (maybe rename this package LazyArrays.jl in that case). Another approach is to use MappedArrays.jl, and make a Lazy matrix corresponding to `[(i,j) for i=1:n, j=1:m]`, in which 
case one could do.

**Comment by dlfivefifty** [comment]
For example, `sparse(Zeros(5,5))` wouldn't work properly (that is, make an empty `SparseMatrixCSC`) if you didn't have a special type called `Zeros`.

**Comment by dlfivefifty** [comment]
This should be in https://github.com/dlfivefifty/LazyArrays.jl, see new issue https://github.com/dlfivefifty/LazyArrays.jl/issues/2
