### ISSUE TITLE
Support Colon in reshape overloads

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/FillArrays.jl#85]
https://github.com/JuliaArrays/FillArrays.jl/blob/60235cbb8ad2bf1cf3b781cb9f29902f6f793881/src/FillArrays.jl#L168-L169 these don't support `Colon`, so something like `reshape(A,:,5)` will cause this to create a `ReshapedArray`.

**Comment by dlfivefifty** [comment]
Will merge a PR.

**Comment by ChrisRackauckas** [comment]
For now I'm just working around it

https://github.com/JuliaDiffEq/DiffEqSensitivity.jl/pull/188/files#diff-b988a3a45ad1d677d44ecc1a339c04f0R65

but thought it would be good to document it since it shows up in Zygote backpasses.

**Comment by ChrisRackauckas** [comment]
It also doesn't seem index with colon to give a new `FillArray`, which causes issues with GPUs.

**Comment by dlfivefifty** [comment]
It looks like there are more missing variants:
```julia
julia> reshape(x,(2,3))
2×3 reshape(::Fill{Float64,1,Tuple{Base.OneTo{Int64}}}, 2, 3) with eltype Float64:
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> reshape(Fill(1.0,1,6),Val(1))
6-element reshape(::Fill{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}}, 6) with eltype Float64:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
```
