### ISSUE TITLE
conversion to pointer

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaArrays/FillArrays.jl#88]
We encountered an issue, reported here https://github.com/FluxML/Flux.jl/issues/1055, where some FillArrays ended up in convolutional kernels relying on C libraries, and attempt at converting into pointers resulted in errors. These two lines seemingly solved the problem
```julia
Base.pointer(x::FillArrays.AbstractFill) = pointer(Array(x))
Base.pointer(x::FillArrays.AbstractFill, i::Integer) = pointer(Array(x), i)
``` 
although I'm not sure allocating a new array is appropriate in any context. 
Should we add this definition here?

**Comment by dlfivefifty** [comment]
This seems like a bad idea. Perhaps you want to call ` convert(Array, A)` before passing to C?

**Comment by CarloLucibello** [comment]
yep, it does seem a bad idea. That piece of code works also on SubArrays, so  convert(Array, A) is not an option, unless I special case the code for fillarrays, which can be done although is a bit annoying

**Comment by dlfivefifty** [comment]
You can use ArrayLayouts.jl for this:
```julia
julia> using FillArrays, ArrayLayouts

julia> convert2columnmajor(A) = convert2columnmajor(MemoryLayout(typeof(A)), A);


julia> convert2columnmajor(_, A) = convert(Array, A)
convert2columnmajor (generic function with 3 methods)

julia> convert2columnmajor(::AbstractColumnMajor, A) = A
convert2columnmajor (generic function with 3 methods)

julia> convert2columnmajor(Fill(5,10))
10-element Array{Int64,1}:
 5
 5
 5
 5
 5
 5
 5
 5
 5
 5

julia> convert2columnmajor(view([1,2,3],1:2))
2-element view(::Array{Int64,1}, 1:2) with eltype Int64:
 1
 2

julia> convert2columnmajor(view([1,2,3],[1,3]))
2-element Array{Int64,1}:
 1
```

**Comment by CarloLucibello** [comment]
thanks!
