### ISSUE TITLE
additional constructors for Zeros and Ones

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaArrays/FillArrays.jl#94]
It would be nice to have `Zeros(eltype, dims)` and `Ones(eltype, dims)`, in analogy to `zeros` and `ones` functions

**Comment by dlfivefifty** [comment]
What do these do that `Zeros{eltype}(dims)` / `Ones{eltype}(dims)` do not? 

In principle it's not a good idea to have synonyms in code, as it makes find-and-replace more difficult, for example.
